'use client';

import { useState, useRef, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Play, Pause, Volume2, VolumeX, Maximize, Settings, Subtitles } from 'lucide-react';

interface VideoPlayerProps {
  src?: string;
  title: string;
  /** URL to a WebVTT subtitle file generated by Whisper STT on the backend. */
  subtitleSrc?: string;
}

export function VideoPlayer({ src, title, subtitleSrc }: VideoPlayerProps) {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isMuted, setIsMuted] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [progress, setProgress] = useState(0);
  // Subtitles default ON for deaf accessibility
  const [showSubtitles, setShowSubtitles] = useState(true);
  const videoRef = useRef<HTMLVideoElement>(null);

  // Wire up video event listeners
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;

    const handleTimeUpdate = () => {
      setCurrentTime(video.currentTime);
      setProgress((video.currentTime / video.duration) * 100 || 0);
    };
    const handleLoadedMetadata = () => setDuration(video.duration);
    const handleLoadedData = () => {
      // Apply subtitle visibility once tracks are ready
      const tracks = video.textTracks;
      for (let i = 0; i < tracks.length; i++) {
        tracks[i].mode = showSubtitles ? 'showing' : 'hidden';
      }
    };
    const handlePlay = () => setIsPlaying(true);
    const handlePause = () => setIsPlaying(false);

    video.addEventListener('timeupdate', handleTimeUpdate);
    video.addEventListener('loadedmetadata', handleLoadedMetadata);
    video.addEventListener('loadeddata', handleLoadedData);
    video.addEventListener('play', handlePlay);
    video.addEventListener('pause', handlePause);

    return () => {
      video.removeEventListener('timeupdate', handleTimeUpdate);
      video.removeEventListener('loadedmetadata', handleLoadedMetadata);
      video.removeEventListener('loadeddata', handleLoadedData);
      video.removeEventListener('play', handlePlay);
      video.removeEventListener('pause', handlePause);
    };
  }, [src, showSubtitles]);

  // Sync subtitle track visibility whenever the toggle changes
  useEffect(() => {
    const video = videoRef.current;
    if (!video || !subtitleSrc) return;
    const tracks = video.textTracks;
    for (let i = 0; i < tracks.length; i++) {
      tracks[i].mode = showSubtitles ? 'showing' : 'hidden';
    }
  }, [showSubtitles, subtitleSrc]);

  const togglePlay = () => {
    if (!videoRef.current) return;
    if (isPlaying) {
      videoRef.current.pause();
    } else {
      videoRef.current.play();
    }
  };

  const toggleMute = () => {
    if (!videoRef.current) return;
    videoRef.current.muted = !isMuted;
    setIsMuted(!isMuted);
  };

  const toggleSubtitles = () => {
    const newShow = !showSubtitles;
    setShowSubtitles(newShow);
    const video = videoRef.current;
    if (video && subtitleSrc) {
      const tracks = video.textTracks;
      for (let i = 0; i < tracks.length; i++) {
        tracks[i].mode = newShow ? 'showing' : 'hidden';
      }
    }
  };

  const handleProgressClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if (!videoRef.current) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const pos = (e.clientX - rect.left) / rect.width;
    videoRef.current.currentTime = pos * videoRef.current.duration;
  };

  const handleFullscreen = () => {
    if (!videoRef.current) return;
    if (document.fullscreenElement) {
      document.exitFullscreen();
    } else {
      videoRef.current.requestFullscreen();
    }
  };

  const formatTime = (seconds: number): string => {
    if (isNaN(seconds)) return '0:00';
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  return (
    <div className="bg-black rounded-lg overflow-hidden">
      <div className="relative aspect-video bg-gray-900 flex items-center justify-center">
        {src ? (
          <video
            ref={videoRef}
            className="w-full h-full"
            aria-label={title}
            crossOrigin="anonymous"
          >
            <source src={src} type="video/mp4" />
            {subtitleSrc && (
              <track
                kind="subtitles"
                label="Subtitles"
                src={subtitleSrc}
                srcLang="en"
                default
              />
            )}
            Your browser does not support the video tag.
          </video>
        ) : (
          <div className="text-white text-center p-8">
            <Play className="h-16 w-16 mx-auto mb-4 opacity-50" aria-hidden="true" />
            <p className="text-lg">Video will be displayed here</p>
          </div>
        )}
      </div>

      {/* Video Controls */}
      <div
        className="bg-gray-800 p-4 flex items-center gap-4"
        role="toolbar"
        aria-label="Video controls"
      >
        {/* Subtitle availability indicator */}
        {subtitleSrc ? (
          <span className="text-xs text-green-400 mr-2" aria-label="Closed captions available">
            CC
          </span>
        ) : (
          <span className="text-xs text-yellow-500 mr-2" title="Subtitles are being generated">
            CC…
          </span>
        )}

        <Button
          variant="ghost"
          size="icon"
          onClick={togglePlay}
          className="text-white hover:bg-gray-700"
          aria-label={isPlaying ? 'Pause video' : 'Play video'}
          disabled={!src}
        >
          {isPlaying ? (
            <Pause className="h-5 w-5" aria-hidden="true" />
          ) : (
            <Play className="h-5 w-5" aria-hidden="true" />
          )}
        </Button>

        <Button
          variant="ghost"
          size="icon"
          onClick={toggleMute}
          className="text-white hover:bg-gray-700"
          aria-label={isMuted ? 'Unmute video' : 'Mute video'}
          disabled={!src}
        >
          {isMuted ? (
            <VolumeX className="h-5 w-5" aria-hidden="true" />
          ) : (
            <Volume2 className="h-5 w-5" aria-hidden="true" />
          )}
        </Button>

        <div
          className="flex-1 bg-gray-700 h-1 rounded-full cursor-pointer"
          onClick={handleProgressClick}
          role="progressbar"
          aria-valuenow={Math.round(progress)}
          aria-valuemin={0}
          aria-valuemax={100}
          aria-label={`Video progress: ${Math.round(progress)}%`}
        >
          <div
            className="bg-blue-500 h-1 rounded-full transition-all"
            style={{ width: `${progress}%` }}
          />
        </div>

        <span className="text-white text-sm min-w-[80px] text-right" aria-live="polite">
          {formatTime(currentTime)} / {formatTime(duration)}
        </span>

        <Button
          variant="ghost"
          size="icon"
          onClick={toggleSubtitles}
          className={`text-white hover:bg-gray-700 ${showSubtitles && subtitleSrc ? 'bg-gray-600' : ''}`}
          aria-label={showSubtitles ? 'Hide subtitles' : 'Show subtitles'}
          disabled={!src || !subtitleSrc}
          title={!subtitleSrc ? 'Subtitles are being generated…' : undefined}
        >
          <Subtitles className="h-5 w-5" aria-hidden="true" />
        </Button>

        <Button
          variant="ghost"
          size="icon"
          className="text-white hover:bg-gray-700"
          aria-label="Settings"
          disabled
        >
          <Settings className="h-5 w-5" aria-hidden="true" />
        </Button>

        <Button
          variant="ghost"
          size="icon"
          onClick={handleFullscreen}
          className="text-white hover:bg-gray-700"
          aria-label="Fullscreen"
          disabled={!src}
        >
          <Maximize className="h-5 w-5" aria-hidden="true" />
        </Button>
      </div>
    </div>
  );
}
